version: "3.7"

x-airflow-common:
  &airflow-common
  
  build:
    context: .
    dockerfile: Dockerfile

  env_file: 
    - "./env/.env"
    
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    AIRFLOW_CONN_METADATA_DB: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    AIRFLOW_VAR__METADATA_DB_SCHEMA: airflow
    AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 5
    AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
    _AIRFLOW_DB_MIGRATE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
    _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
  
  volumes:
    - ${AIRFLOW_PROJ_DIR}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR}/plugins:/opt/airflow/plugins
    
services:
  postgres:
    image: postgres:17
    
    ports:
      - "5432:5432"
    
    env_file: 
      - "./env/.env"
      
    volumes:
      - "backup_postgresql_airflow:/var/lib/postgresql/data"
   
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
  webserver:
    <<: *airflow-common
    command: webserver
    
    ports:
      - "8080:8080"
    
    depends_on:
      - postegres
    
  scheduler:
    <<: *airflow-common
    command: scheduler
       
    depends_on:
      - postegres
      - webserver
    
    
    
